export let treeSampleData: Object[] = [{
    "id": 2997186,
    "sourceFileName": "\"An50Kn50LaanAaterbetalnLaes.java\"",
    "fqn": "\"se.csn.stis.an.lan.server.kn50.An50Kn50LaanAaterbetalnLaes\"",
    "fileName": "\"/se/csn/stis/an/lan/server/kn50/An50Kn50LaanAaterbetalnLaes.class\"",
    "name": "\"An50Kn50LaanAaterbetalnLaes\"",
    "children": [{
        "id": 2996111,
        "sourceFileName": "\"Kn5000LaanAaterbetalnLaes.java\"",
        "fqn": "\"se.csn.stis.an.lan.server.kn50.lab.Kn5000LaanAaterbetalnLaes\"",
        "fileName": "\"/se/csn/stis/an/lan/server/kn50/lab/Kn5000LaanAaterbetalnLaes.class\"",
        "name": "\"Kn5000LaanAaterbetalnLaes\"",
        "children": [{
            "id": 2995411,
            "sourceFileName": "\"Kn5008HaendelserLaes.java\"",
            "fqn": "\"se.csn.stis.an.lan.server.kn50.lab.Kn5008HaendelserLaes\"",
            "fileName": "\"/se/csn/stis/an/lan/server/kn50/lab/Kn5008HaendelserLaes.class\"",
            "name": "\"Kn5008HaendelserLaes\"",
            "children": [{
                "id": 1384935,
                "sourceFileName": "\"IAn964ATjaensteantAabKontr.java\"",
                "fqn": "\"se.csn.stis.an.service.api.an964.IAn964ATjaensteantAabKontr\"",
                "fileName": "\"/se/csn/stis/an/service/api/an964/IAn964ATjaensteantAabKontr.class\"",
                "name": "\"IAn964ATjaensteantAabKontr\"",
                "children": null
            }, {
                "id": 1410869,
                "sourceFileName": "\"IPsma006AMaEHaendelseKontrollStub.java\"",
                "fqn": "\"se.csn.stis.an.stub.api.psma006.IPsma006AMaEHaendelseKontrollStub\"",
                "fileName": "\"/se/csn/stis/an/stub/api/psma006/IPsma006AMaEHaendelseKontrollStub.class\"",
                "name": "\"IPsma006AMaEHaendelseKontrollStub\"",
                "children": null
            }]
        }, {
            "id": 2994895,
            "sourceFileName": "\"Kn5002AerendeHndDokumentLaes.java\"",
            "fqn": "\"se.csn.stis.an.lan.server.kn50.lab.Kn5002AerendeHndDokumentLaes\"",
            "fileName": "\"/se/csn/stis/an/lan/server/kn50/lab/Kn5002AerendeHndDokumentLaes.class\"",
            "name": "\"Kn5002AerendeHndDokumentLaes\"",
            "children": null
        }, {
            "id": 2995267,
            "sourceFileName": "\"Kn5009DokumentLaes.java\"",
            "fqn": "\"se.csn.stis.an.lan.server.kn50.lab.Kn5009DokumentLaes\"",
            "fileName": "\"/se/csn/stis/an/lan/server/kn50/lab/Kn5009DokumentLaes.class\"",
            "name": "\"Kn5009DokumentLaes\"",
            "children": [{
                "id": 1412398,
                "sourceFileName": "\"IPsar021ABlankettbenmHaemtaStub.java\"",
                "fqn": "\"se.csn.stis.an.stub.api.psar021.IPsar021ABlankettbenmHaemtaStub\"",
                "fileName": "\"/se/csn/stis/an/stub/api/psar021/IPsar021ABlankettbenmHaemtaStub.class\"",
                "name": "\"IPsar021ABlankettbenmHaemtaStub\"",
                "children": null
            }, {
                "id": 1402758,
                "sourceFileName": "\"IPsba185ADokumentLaesStub.java\"",
                "fqn": "\"se.csn.stis.an.stub.api.psba185.IPsba185ADokumentLaesStub\"",
                "fileName": "\"/se/csn/stis/an/stub/api/psba185/IPsba185ADokumentLaesStub.class\"",
                "name": "\"IPsba185ADokumentLaesStub\"",
                "children": null
            }]
        }, {
            "id": 2994415,
            "sourceFileName": "\"Kn5001LaanLaes.java\"",
            "fqn": "\"se.csn.stis.an.lan.server.kn50.lab.Kn5001LaanLaes\"",
            "fileName": "\"/se/csn/stis/an/lan/server/kn50/lab/Kn5001LaanLaes.class\"",
            "name": "\"Kn5001LaanLaes\"",
            "children": [{
                "id": 1383483,
                "sourceFileName": "\"IAn5F4ALaanUppsagtFinns.java\"",
                "fqn": "\"se.csn.stis.an.service.api.an5f4.IAn5F4ALaanUppsagtFinns\"",
                "fileName": "\"/se/csn/stis/an/service/api/an5f4/IAn5F4ALaanUppsagtFinns.class\"",
                "name": "\"IAn5F4ALaanUppsagtFinns\"",
                "children": null
            }, {
                "id": 1400174,
                "sourceFileName": "\"IPspa100APersonCsnnrLaesStub.java\"",
                "fqn": "\"se.csn.stis.an.stub.api.pspa100.IPspa100APersonCsnnrLaesStub\"",
                "fileName": "\"/se/csn/stis/an/stub/api/pspa100/IPspa100APersonCsnnrLaesStub.class\"",
                "name": "\"IPspa100APersonCsnnrLaesStub\"",
                "children": null
            }, {
                "id": 1386217,
                "sourceFileName": "\"IAn512ALaanSkuldBeraekna.java\"",
                "fqn": "\"se.csn.stis.an.service.api.an512.IAn512ALaanSkuldBeraekna\"",
                "fileName": "\"/se/csn/stis/an/service/api/an512/IAn512ALaanSkuldBeraekna.class\"",
                "name": "\"IAn512ALaanSkuldBeraekna\"",
                "children": null
            }, {
                "id": 1397965,
                "sourceFileName": "\"IPsar001AParameterlaesStub.java\"",
                "fqn": "\"se.csn.stis.an.stub.api.psar001.IPsar001AParameterlaesStub\"",
                "fileName": "\"/se/csn/stis/an/stub/api/psar001/IPsar001AParameterlaesStub.class\"",
                "name": "\"IPsar001AParameterlaesStub\"",
                "children": null
            }]
        }, {
            "id": 1395960,
            "sourceFileName": "\"IPsco025AHandlaeggUseridLaesStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.psco025.IPsco025AHandlaeggUseridLaesStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/psco025/IPsco025AHandlaeggUseridLaesStub.class\"",
            "name": "\"IPsco025AHandlaeggUseridLaesStub\"",
            "children": null
        }, {
            "id": 1383483,
            "sourceFileName": "\"IAn5F4ALaanUppsagtFinns.java\"",
            "fqn": "\"se.csn.stis.an.service.api.an5f4.IAn5F4ALaanUppsagtFinns\"",
            "fileName": "\"/se/csn/stis/an/service/api/an5f4/IAn5F4ALaanUppsagtFinns.class\"",
            "name": "\"IAn5F4ALaanUppsagtFinns\"",
            "children": null
        }, {
            "id": 1385225,
            "sourceFileName": "\"IAn950ACsnorgLaensraettLaes.java\"",
            "fqn": "\"se.csn.stis.an.service.api.an950.IAn950ACsnorgLaensraettLaes\"",
            "fileName": "\"/se/csn/stis/an/service/api/an950/IAn950ACsnorgLaensraettLaes.class\"",
            "name": "\"IAn950ACsnorgLaensraettLaes\"",
            "children": null
        }, {
            "id": 1410493,
            "sourceFileName": "\"IPspa138APersonGiltAdrHaemtaStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.pspa138.IPspa138APersonGiltAdrHaemtaStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/pspa138/IPspa138APersonGiltAdrHaemtaStub.class\"",
            "name": "\"IPspa138APersonGiltAdrHaemtaStub\"",
            "children": null
        }, {
            "id": 1402191,
            "sourceFileName": "\"IPspa183AAdressreturerLaesStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.pspa183.IPspa183AAdressreturerLaesStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/pspa183/IPspa183AAdressreturerLaesStub.class\"",
            "name": "\"IPspa183AAdressreturerLaesStub\"",
            "children": null
        }, {
            "id": 1398927,
            "sourceFileName": "\"IPsba164AObesvBrevarFinnsKntrStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.psba164.IPsba164AObesvBrevarFinnsKntrStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/psba164/IPsba164AObesvBrevarFinnsKntrStub.class\"",
            "name": "\"IPsba164AObesvBrevarFinnsKntrStub\"",
            "children": null
        }, {
            "id": 1410263,
            "sourceFileName": "\"IPspa123APersonEtjaenstLaesStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.pspa123.IPspa123APersonEtjaenstLaesStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/pspa123/IPspa123APersonEtjaenstLaesStub.class\"",
            "name": "\"IPspa123APersonEtjaenstLaesStub\"",
            "children": null
        }, {
            "id": 1397965,
            "sourceFileName": "\"IPsar001AParameterlaesStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.psar001.IPsar001AParameterlaesStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/psar001/IPsar001AParameterlaesStub.class\"",
            "name": "\"IPsar001AParameterlaesStub\"",
            "children": null
        }, {
            "id": 1395206,
            "sourceFileName": "\"IPsge079ATransaktionsloggSkapaStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.psge079.IPsge079ATransaktionsloggSkapaStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/psge079/IPsge079ATransaktionsloggSkapaStub.class\"",
            "name": "\"IPsge079ATransaktionsloggSkapaStub\"",
            "children": null
        }, {
            "id": 1409842,
            "sourceFileName": "\"IPspa099APersSekrPershistLaesStub.java\"",
            "fqn": "\"se.csn.stis.an.stub.api.pspa099.IPspa099APersSekrPershistLaesStub\"",
            "fileName": "\"/se/csn/stis/an/stub/api/pspa099/IPspa099APersSekrPershistLaesStub.class\"",
            "name": "\"IPspa099APersSekrPershistLaesStub\"",
            "children": null
        }]
    }, {
        "id": 3037527,
        "sourceFileName": "\"Tran191ALaanAakrIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran191.Tran191ALaanAakrIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran191/Tran191ALaanAakrIs.class\"",
        "name": "\"Tran191ALaanAakrIs\"",
        "children": null
    }, {
        "id": 3035441,
        "sourceFileName": "\"Tran025AAerendeAabetIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran025.Tran025AAerendeAabetIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran025/Tran025AAerendeAabetIs.class\"",
        "name": "\"Tran025AAerendeAabetIs\"",
        "children": null
    }, {
        "id": 3029170,
        "sourceFileName": "\"Tran026AAerendeAabetSi.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran026.Tran026AAerendeAabetSi\"",
        "fileName": "\"/se/csn/stis/an/translator/tran026/Tran026AAerendeAabetSi.class\"",
        "name": "\"Tran026AAerendeAabetSi\"",
        "children": null
    }, {
        "id": 3035049,
        "sourceFileName": "\"Tran083ADokumentAabetIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran083.Tran083ADokumentAabetIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran083/Tran083ADokumentAabetIs.class\"",
        "name": "\"Tran083ADokumentAabetIs\"",
        "children": null
    }, {
        "id": 3031238,
        "sourceFileName": "\"Tran133AHaendelseAabetIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran133.Tran133AHaendelseAabetIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran133/Tran133AHaendelseAabetIs.class\"",
        "name": "\"Tran133AHaendelseAabetIs\"",
        "children": null
    }, {
        "id": 3027310,
        "sourceFileName": "\"Tran157AIndivAvisVillkIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran157.Tran157AIndivAvisVillkIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran157/Tran157AIndivAvisVillkIs.class\"",
        "name": "\"Tran157AIndivAvisVillkIs\"",
        "children": null
    }, {
        "id": 3035869,
        "sourceFileName": "\"Tran159AIndivBetalvillkIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran159.Tran159AIndivBetalvillkIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran159/Tran159AIndivBetalvillkIs.class\"",
        "name": "\"Tran159AIndivBetalvillkIs\"",
        "children": null
    }, {
        "id": 3040423,
        "sourceFileName": "\"Tran066ABetalningsregelSi.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran066.Tran066ABetalningsregelSi\"",
        "fileName": "\"/se/csn/stis/an/translator/tran066/Tran066ABetalningsregelSi.class\"",
        "name": "\"Tran066ABetalningsregelSi\"",
        "children": null
    }, {
        "id": 3026984,
        "sourceFileName": "\"Tran065ABetalningsregelIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran065.Tran065ABetalningsregelIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran065/Tran065ABetalningsregelIs.class\"",
        "name": "\"Tran065ABetalningsregelIs\"",
        "children": null
    }, {
        "id": 3035257,
        "sourceFileName": "\"Tran084ADokumentAabetSi.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran084.Tran084ADokumentAabetSi\"",
        "fileName": "\"/se/csn/stis/an/translator/tran084/Tran084ADokumentAabetSi.class\"",
        "name": "\"Tran084ADokumentAabetSi\"",
        "children": null
    }, {
        "id": 3026224,
        "sourceFileName": "\"Tran013AAarsavgiftIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran013.Tran013AAarsavgiftIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran013/Tran013AAarsavgiftIs.class\"",
        "name": "\"Tran013AAarsavgiftIs\"",
        "children": null
    }, {
        "id": 3034470,
        "sourceFileName": "\"Tran190ALaanSi.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran190.Tran190ALaanSi\"",
        "fileName": "\"/se/csn/stis/an/translator/tran190/Tran190ALaanSi.class\"",
        "name": "\"Tran190ALaanSi\"",
        "children": null
    }, {
        "id": 3030324,
        "sourceFileName": "\"Tran217APersonAabetIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran217.Tran217APersonAabetIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran217/Tran217APersonAabetIs.class\"",
        "name": "\"Tran217APersonAabetIs\"",
        "children": null
    }, {
        "id": 3026758,
        "sourceFileName": "\"Tran218APersonAabetSi.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran218.Tran218APersonAabetSi\"",
        "fileName": "\"/se/csn/stis/an/translator/tran218/Tran218APersonAabetSi.class\"",
        "name": "\"Tran218APersonAabetSi\"",
        "children": null
    }, {
        "id": 3039453,
        "sourceFileName": "\"Tran189ALaanIs.java\"",
        "fqn": "\"se.csn.stis.an.translator.tran189.Tran189ALaanIs\"",
        "fileName": "\"/se/csn/stis/an/translator/tran189/Tran189ALaanIs.class\"",
        "name": "\"Tran189ALaanIs\"",
        "children": null
    }]
}];